version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: inventory-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: inventory_db
    volumes:
      - mongodb_data:/data/db
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    networks:
      - inventory-network

  ms-inventario:
    build: .
    container_name: ms-inventario
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: inventory_db
    networks:
      - inventory-network

volumes:
  mongodb_data:

networks:
  inventory-network:
    driver: bridge
